### ISSUE TITLE
Old version of Cats Effect

### ISSUE THREAD

**Issue by adamnfish** [criteo/lolhttp#63]
The `build.sbt` file seems to mention `v0.4` of `cats-effect` although in practice it seems to pull in `v0.8`. The latest version is `1.0.0-RC`. It would be great to see this library update to the stable `1.x` branch, which offers more features.

Explicitly pulling in cats-effect at the latest version *seems* to work, although there is no guarantee of binary compatibility so I may stumble across a feature that causes an exception at runtime.

**Comment by guillaumebort** [comment]
Pull request #64 update everything. As it is a big change I would be interested by your feedback!
