### ISSUE TITLE
Client.runSync does not follow redirect url

### ISSUE THREAD

**Issue by chungonn** [criteo/lolhttp#65]
I found that the Client.runSync does not follow redirect url. I have created a testcase to reproduce the problem.

package samples

import java.io.{BufferedReader, InputStreamReader}
import java.net.{HttpURLConnection, URL}
import java.nio.charset.Charset
import java.util.stream.Collectors

import lol.http._
import org.scalatest.FunSuite

import scala.concurrent.ExecutionContext.Implicits.global

class RedirectSuite extends FunSuite {

  test("Redirect"){

    val SA = Server.listen(8888){
      case GET at url"/service-a" =>
        println("Service A, redirecting to Service B")
        Redirect("http://localhost:9999/service-b")

      case _ =>
        NotFound("Service A not found")
    }

    val SB = Server.listen(9999){
      case GET at url"/service-b" =>
        println("Service B.. Got It!")
        Ok("Got It!")

      case r =>
        println(s"Route not found ${r.url}")
        NotFound(s"Route not found ${r.url}")
    }

// Client.runSync is broken
//    Client.runSync(Get("http://localhost:8888/service-a")){resp =>
//      resp.readAs[String].map(body => println("Body " + body))
//    }

    val (status, body) = get("http://localhost:8888/service-a")
    println(s"status ${status}, body ${body}")

    SA.stop()
    SB.stop()

  }

  def get(url: String, timeout: Int = 30, enc: String = "UTF-8"): (Int, String) = {
    val con = createConnection("GET", url, timeout)
    val responseCode = con.getResponseCode

    //Reading response
    val charset = Charset.forName(enc)
    val in = new BufferedReader(new InputStreamReader(con.getInputStream, charset))

    try {
      val content = in.lines().collect(Collectors.joining("\n"))
      (responseCode, content)
    }finally{
      in.close()
    }

  }

  private def createConnection(method: String, url: String, timeout:Int): HttpURLConnection = {
    val obj = new URL(url)
    val con = obj.openConnection().asInstanceOf[HttpURLConnection]
    con.setRequestMethod(method)
    con.setConnectTimeout(timeout * 1000)
    con.setAllowUserInteraction(false)
    con.setRequestProperty("Accept", "*/*")
    con.setRequestProperty("User-Agent", "")
    con
  }

}

**Comment by guillaumebort** [comment]
Should be fixed in `0.11.0`
